[package]
name = "snipcomp"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.11.1"
clap = { version = "4.0", features = ["derive"] }
tempfile = "3.15.0"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"

